### PR TITLE
fix: code quality issues

### PR DESCRIPTION
**Pull request by withshubh**
#### Description
This PR fixes a few issues that were affecting the code quality.

#### Summary of changes

- Use literal syntax instead of function calls to create data structure
- Remove reimported module
- Use `is` to compare type of objects
- Access attribute directly
- Remove unnecessary `del` statement from local scope

### CODE REVIEW

**Comment by boba-and-beer** [comment]
Thank you for your PR.

**Comment by withshubh** [comment]
@boba-and-beer :wave: 

I would like to inform you that these issues were caught by [DeepSource](https://deepsource.io/) on my fork of this repository. There are many more existing issues which you can fix. Have a look at the issues caught in this repository by DeepSource [here](https://deepsource.io/gh/withshubh/vectorhub/issues/?category=recommended).

DeepSource is a code review automation tool that detects code quality issues and helps you to automatically fix some of them. You can use DeepSource to track test coverage, Detect problems in Dockerfiles, etc. in addition to detecting issues in code.

Can I submit a new PR with the configuration file which I used to configure the analysis?
You can merge the configuration file to continuously analyze the repo and fix code quality issues.

**Comment by boba-and-beer** [comment]
I think much of this can be fixed with pyLint so I don't think there is a need for PR. We don't enforce PyLint because we don't want to bog ourselves down to strict adherence to rules while we continue to add code. Thank you for your interest though and I do like the DeepSource UI.

**Comment by withshubh** [comment]
@boba-and-beer I got it. Thank You :sparkling_heart:

**Pull request merged**
